### ISSUE TITLE
Revisión App Nativas

### ISSUE THREAD

**Issue by jhrubiano10** [jhrubiano10/pruebas_automaticas#1]
Olga revisará las [aplicaciones nativas], para el día lunes 28 de Agosto de 2017.

##  Entregables

* Listado de pantallazo de las aplicaciones relacionados a funcionalidades

[aplicaciones nativas]:https://github.com/jhrubiano10/pruebas_automaticas/wiki/24-08-2017

**Comment by olvegam** [comment]
# Revisión app Nativas. 

Se revisó la documentación de las aplicaciones. Se crearon las páginas de revisión en la Wiki. 

## Realización de Pruebas Exploratorias.

Se realizó prueba exploratoria a KouChat, cuyo resultado fallido ( la sala de chat no reconoce a los otros usuarios en la misma red) se publicó en la carpeta de pruebas de la app nativa en el repositorio. 

En cuanto a LoopHabitTracker, como resultado de la revisión de la documentación se concluye que su funcionalidad es muy reducida (Principalmente dos casos de uso) y sus características limitadas para el ámbito de pruebas a realizar en el curso (Conectividad, Seguridad, Concurrencia, etc.).  Se inicia búsqueda de app de reemplazo.
