### ISSUE TITLE
Revisión app web

### ISSUE THREAD

**Issue by olvegam** [jhrubiano10/pruebas_automaticas#2]
Jorge revisará la documentación de la aplicación web para descubrir sus características y poder completar el contexto de la estrategia de pruebas. 

Estas características las publicará en la Wiki del repositorio y se revisarán el lunes 28 de agosto de 2017.

**Comment by jhrubiano10** [comment]
# Revisión aplicación web

Se ha revisado la aplicación web Ghost, se ha creado la entrada [28 08 2017 Revisión Aplicación Web (Ghost)] en la cual se listan las funcionalidades del sistema, así como el modo de instalación de la aplicación.

## Realización de Pruebas vía Cypress.

* Se están revisando las pruebas con la herramienta Cypress.
* Se han creado algunas pruebas con está herramienta, las cuales ya se encuentran alojadas en el [repositorio de código]

## Pruebas realizadas en el momento.

* Visitar un Blog.
* Suscribirse a un Blog.
* Mostrar entradas de un usuario.
* Autenticación fallida  - Correo no existe.
* Autenticación fallida  - Contraseña inválida.
* Autenticar usuario.
* Crear una nueva entrada del Blog.

Jorge Rubiano.

[28 08 2017 Revisión Aplicación Web (Ghost)]:https://github.com/jhrubiano10/pruebas_automaticas/wiki/28-08-2017---Revisi%C3%B3n-Aplicaci%C3%B3n-Web-(Ghost)
[repositorio de código]:https://github.com/jhrubiano10/pruebas_automaticas/blob/master/aplicativo_web/pruebas_ghost/pruebas_cypress/test_cypress.js

**Comment by jhrubiano10** [comment]
Sí cumple con el objetivo planteado.
