### ISSUE TITLE
Reunión de cierre de estrategia de pruebas y revisión de las app (web y nativas). 

### ISSUE THREAD

**Issue by olvegam** [jhrubiano10/pruebas_automaticas#3]
El lunes 28 de agosto de 2017, se realizará reunión para cerrar el proceso de revisión de las caractarísticas de las app, completar la estrategia de pruebas (Tienen pendiente en el contexto las características) y establecer el plan de acción para ejecutar la estrategia de pruebas de la app web.

**Comment by jhrubiano10** [comment]
La reunión se aplazó, realizándose el día martes 29 de Agosto de 2017, se cierra issue #2 relacionado a la revisión de la aplicación web, el issue #1  queda pendiente y se resolverá el día de mañana 30 de Agosto de 2017. En la clase se dará una revisión final.

**Comment by jhrubiano10** [comment]
Se cierra este Issue.
