### ISSUE TITLE
Pruebas sobre la app Web para búsquedas de error. 

### ISSUE THREAD

**Issue by olvegam** [jhrubiano10/pruebas_automaticas#5]
Aumentar los tipos de prueba en búsqueda de errores.

**Comment by jhrubiano10** [comment]
## 01/09/2017

* Se han realizado pruebas de la aplicación con Cypress.io con éste se ha evidenciado que la aplicación no tiene problemas a nivel de vista, haciendo pruebas de tipo E2E.

* Se ha encontrado una **vulnerabilidad** del sistema en la creación de nuevas entradas de un Post, ya que el editor manejado permite la inserción de código html/js sin realizar una limpieza de éste, permitiendo la inserción de código Javascript, provocando que sea vulnerable a un ataque de tipo [XSS], de tipo [persistente], la vulnerabilidad esta presente en el complemento [Codemirror]

* Otra herramienta que se ha explorado es el uso de la herramienta [sqlmap] para buscar vulnerabilidad de tipo SQLInjection, hasta el momento no se ha encontrado ninguna vulnerabilidad de este tipo.

* Se han hecho pruebas de accesibilidad del sistema con la herramienta [Wave], se encontraron algunos errores relacionados a la ausencia de elementos que ayudaran a los sistemas tipo "Screen readers" a leer lo que se encuentra en la página.

[XSS]:https://www.owasp.org/index.php/Cross-site_Scripting_(XSS)
[persistente]:https://www.acunetix.com/blog/articles/persistent-xss/
[sqlmap]:http://sqlmap.org/
[Codemirror]:https://codemirror.net/
[Wave]:http://wave.webaim.org/

**Comment by jhrubiano10** [comment]
Se cierra el issue.
