### ISSUE TITLE
Reunión 1 de septiembre de 2017

### ISSUE THREAD

**Issue by olvegam** [jhrubiano10/pruebas_automaticas#6]
Revisar la realización de estrategia de pruebas para ver el nivel de avance y hacer los ajustes pertinentes.

**Comment by jhrubiano10** [comment]
## Reunión realizada.

* Se ha realizado la reunión en la cual se han visto los avances realizados para la presentación del día 06 de Septiembre de 2017.

* Se avanzará en más pruebas en la aplicación web, se iniciarán las pruebas en las aplicaciones móviles.

* Se explorará otra aplicación nativa que pueda reemplazar a KouChat, ya que se evidenció en las pruebas exploratorias que está no funciona.

Se cierra en issue.
