### ISSUE TITLE
Reunión lunes 4 de Septiembre de 2017

### ISSUE THREAD

**Issue by olvegam** [jhrubiano10/pruebas_automaticas#7]
Realización presentación de resumen para Reporte.

**Comment by jhrubiano10** [comment]
## Reunión 04 de Septiembre de 2014

* Se ha revisado los avances de los descubrimientos web.
* Se habló de los pruebas testing monkey para aplicaciones Móviles.
* Se decidió escoger la aplicación nativa [AntennaPod] reemplazando la aplicación [KouChat]
* @olvegam realizará pruebas exploratorias a esta aplicación.

[AntennaPod]:https://github.com/AntennaPod/AntennaPod
[KouChat]:https://github.com/jhrubiano10/pruebas_automaticas/wiki/28-08-2017-%22KouChat%22-Native-App-check.
